name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # need bleeding edge aether now
    - name: Check out aether
      uses: actions/checkout@v4
      with:
        repository: dtqec/aether
        path: aether
    - name: Check out anatevka
      uses: actions/checkout@v4
      with:
        path: anatevka
    - name: Initialize Lisp
      run: |
        sudo apt install sbcl
        mkdir -p ${HOME}/quicklisp/local-projects
        cp -R aether ${HOME}/quicklisp/local-projects/aether
        curl -o /tmp/quicklisp.lisp "http://beta.quicklisp.org/quicklisp.lisp"
        sbcl --noinform --non-interactive \
             --load /tmp/quicklisp.lisp \
             --eval '(quicklisp-quickstart:install)'
        WD=$(pwd | xargs dirname)
        echo >> ~/.sbclrc
        echo '#-quicklisp(let ((i(merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))(when(probe-file i)(load i)))' >> ~/.sbclrc
        echo "#+quicklisp(push \"${WD}/\" ql:*local-project-directories*)" >> ~/.sbclrc
        rm -f /tmp/quicklisp.lisp
    - name: Run the test suite
      run: |
        # run the tests via the Makefile
        cd anatevka
        sbcl --version
        sbcl --noinform --non-interactive --eval '(ql:quickload "anatevka-tests")'
        make test
